
version: '{build}.0.0-dev'
configuration: Release
os: Visual Studio 2015
pull_requests:
  do_not_increment_build_number: true

environment:
  nuget_apiKey:
    secure: jfcUvHZhgnUboplqTBDWr8mG5PIlrgBv5TA2fhhop4ZSiDxskyy+RtYyeHoduJFR
  myget_apiKey:
    secure: AguzfXNvHBkkDebTyWHK7o9OC5YL3eszT6u7PnzGq2G7ozdUypDlGGpcFsTRYHEc

# Override the 'version' if this is a GH-tag-commit.
# If a Tag, then we only pull down master.
init:
  - ps: if ($env:APPVEYOR_REPO_TAG -eq $TRUE) { if ($env:APPVEYOR_REPO_BRANCH -ne 'master') { Write-Host " !! Commit is Tagged and branch is '$env:APPVEYOR_REPO_BRANCH' - forcing branch to 'master'." -ForegroundColor Red; $env:APPVEYOR_REPO_BRANCH = 'master' } Update-AppveyorBuild -Version "$env:APPVEYOR_REPO_TAG_NAME" }
  - ps: if ($env:APPVEYOR_REPO_BRANCH -ne 'master' -and $env:APPVEYOR_REPO_BRANCH -ne 'dev') { Write-Host " ** Custom branch - so setting build version to '$env:APPVEYOR_BUILD_NUMBER'.0.0-dev-'$env:APPVEYOR_REPO_BRANCH'"; Update-AppveyorBuild -Version "$env:APPVEYOR_BUILD_NUMBER" + ".0.0-dev-" + "$env:APPVEYOR_REPO_BRANCH" }
  - ps: if ($env:APPVEYOR_REPO_BRANCH -ne 'master') { $env:feedSource = "https://www.myget.org/F/openrealestate/api/v2" } else { $env:feedSource = "https://nuget.org" }
  - ps: iex ((new-object net.webclient).DownloadString('https://gist.githubusercontent.com/PureKrome/0f79e25693d574807939/raw/f5b40256fc2ca77d49f1c7773d28406152544c1e/appveyor-build-info.ps'))

before_build:
  - nuget restore

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

build:
  parallel: true
  verbosity: minimal

on_success:
  - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER) { $destinationPath = $env:appveyor_build_folder + ".\file1.ps1"; (new-object net.webclient).DownloadFile('https://raw.githubusercontent.com/PureKrome/PushIt/master/NuGet%20Package%20and%20Publish.ps1', $destinationPath); & $destinationPath -Version $env:appveyor_build_version -NuGet "C:\Tools\NuGet\nuget.exe" -feedSource $env:feedSource -apiKey $env:apiKey -source '.\NuGet\' -destination '.\NuGet\' } else { Write-Host " !! This is a pull request, so no nuget deployment." -ForegroundColor Green }

deploy:
  - provider: WebDeploy
    server: https://openrealestate.scm.azurewebsites.net:443/msdeploy.axd?site=openrealestate
    website: openrealestate
    username: $openrealestate
    password:
      secure: dDSrZ7EKMDsUZfcWehsTJRYRTq4Txg1BfI01FSesmHUYqE3X+ylNVfQrZE51c9hukliPhTa0MyolrkcQB3btsw==
    remove_files: true

cache:
  - packages -> **\packages.config