
version: '1.{build}.0'
configuration: Release

branches:
  only:
    - master

pull_requests:
  do_not_increment_build_number: true

environment:
  apiKey:
    secure: jfcUvHZhgnUboplqTBDWr8mG5PIlrgBv5TA2fhhop4ZSiDxskyy+RtYyeHoduJFR

init:
  - ps: iex ((new-object net.webclient).DownloadString('https://gist.githubusercontent.com/PureKrome/0f79e25693d574807939/raw/fff3b2776dfae3ed9aa69148705a96b698e57e61/appveyor-build-info.ps'))

before_build:
  - nuget restore

assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}'

build:
  parallel: true
  verbosity: minimal

on_success:
  - ps: Write-Host $env:appveyor_build_version
  - ps: '& ".\NuGet\NuGet Package and Publish.ps1" -Version $env:appveyor_build_version -NuGet "C:\Tools\NuGet\nuget.exe" -apiKey $env:apiKey'

# NOTE: there are no artifacts, right now.
#artifacts:
#  - path: '**\*.nupkg'

cache:
  - packages -> **\packages.config


